/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Nextj } from "./Nextj";
import { NextjCountArgs } from "./NextjCountArgs";
import { NextjFindManyArgs } from "./NextjFindManyArgs";
import { NextjFindUniqueArgs } from "./NextjFindUniqueArgs";
import { DeleteNextjArgs } from "./DeleteNextjArgs";
import { NextjService } from "../nextj.service";
@graphql.Resolver(() => Nextj)
export class NextjResolverBase {
  constructor(protected readonly service: NextjService) {}

  async _nextjsMeta(
    @graphql.Args() args: NextjCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Nextj])
  async nextjs(@graphql.Args() args: NextjFindManyArgs): Promise<Nextj[]> {
    return this.service.nextjs(args);
  }

  @graphql.Query(() => Nextj, { nullable: true })
  async nextj(
    @graphql.Args() args: NextjFindUniqueArgs
  ): Promise<Nextj | null> {
    const result = await this.service.nextj(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Nextj)
  async deleteNextj(
    @graphql.Args() args: DeleteNextjArgs
  ): Promise<Nextj | null> {
    try {
      return await this.service.deleteNextj(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
